import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { kakaoWebhook, kakaoOwner, urlsFromMessage, IngressEnv } from '../ingestion/kakao';
import { shortcutCapture } from '../ingestion/shortcut';
import { accountInfo, addEmail, createDeviceCode, createPairingCode, linkKakao, login, pairDevice, signup, verifyEmail } from '../ingestion/auth';
import { deviceLibrary } from '../ingestion/library';
import { processNext, drain } from '../ingestion/processor';
import { analyzeContent, extract, normalizeUrl, youtubeVideoId } from '../lib/pipeline';
import type { Item } from '../lib/domain';
function setup(){const sqlite=new DatabaseSync(':memory:');for(const f of ['drizzle/0000_plain_famine.sql','drizzle/0001_stiff_preak.sql','drizzle/0002_user_identity.sql','drizzle/0003_email_accounts.sql','drizzle/0004_email_verification.sql'])sqlite.exec(readFileSync(f,'utf8').replaceAll('--> statement-breakpoint',''));function prepare(sql:string){let args:unknown[]=[];const api={bind(...values:unknown[]){args=values;return api;},async first(){return sqlite.prepare(sql).get(...args as never[])||null},async all(){return {results:sqlite.prepare(sql).all(...args as never[])}},async run(){const r=sqlite.prepare(sql).run(...args as never[]);return {meta:{changes:Number(r.changes)}}}};return api;}const db={prepare,async batch(stmts:{run:()=>Promise<unknown>}[]){sqlite.exec('BEGIN');try{const out=[];for(const stmt of stmts)out.push(await stmt.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}};return {sqlite,env:{DB:db as unknown as D1Database,KAKAO_SKILL_SECRET:'test-only-32-character-secret-value',KAKAO_BOT_ID:'test-bot'} satisfies IngressEnv};}
function request(text:string,user='user-a',secret='test-only-32-character-secret-value',bot='test-bot'){return new Request('https://ingress.example.com/webhooks/kakao',{method:'POST',headers:{'Content-Type':'application/json','x-nuff-skill-key':secret},body:JSON.stringify({bot:{id:bot},userRequest:{utterance:text,user:{id:user,type:'botUserKey'}}})});}
async function answer(response:Response){return (await response.json() as {template:{outputs:{simpleText:{text:string}}[]}}).template.outputs[0].simpleText.text;}
const fake=async(url:string):Promise<Item>=>({id:crypto.randomUUID(),url,title:'분석 결과',summary:'저장한 원문에서 얻은 결과',claims:['원문 주장'],keywords:['AI','도구','메모리'],topic:'AI & 테크',mode:'ai',platform:'웹사이트',createdAt:new Date().toISOString(),viewed:false});
test('auth fails closed for missing config, wrong secret, wrong bot and malformed payload',async()=>{const {env}=setup();assert.equal((await kakaoWebhook(request('https://example.com','a','wrong'),env)).status,401);assert.equal((await kakaoWebhook(request('https://example.com','a',env.KAKAO_SKILL_SECRET,'other'),env)).status,403);assert.equal((await kakaoWebhook(request('x'),{...env,KAKAO_SKILL_SECRET:''})).status,503);assert.equal((await kakaoWebhook(new Request('https://x.test',{method:'POST',headers:{'x-nuff-skill-key':env.KAKAO_SKILL_SECRET},body:'{}'}),env)).status,400)});
test('capture is durable before ack, normalizes tracking, deduplicates and isolates users',async()=>{const {env,sqlite}=setup();assert.match(await answer(await kakaoWebhook(request('추천 https://example.com/article?utm_source=ig#part'),env)),/1개를 보관/);assert.equal((sqlite.prepare('SELECT COUNT(*) AS n FROM capture_jobs').get() as {n:number}).n,1);assert.match(await answer(await kakaoWebhook(request('https://example.com/article'),env)),/이미 보관/);await kakaoWebhook(request('https://example.com/article','user-b'),env);assert.equal((sqlite.prepare('SELECT COUNT(*) AS n FROM capture_jobs').get() as {n:number}).n,2);assert.notEqual(await kakaoOwner('test-bot','user-a'),await kakaoOwner('test-bot','user-b'));const inbox=await answer(await kakaoWebhook(request('보관함','user-c'),env));assert.match(inbox,/아직 저장한 링크가 없/)});
test('ordinary text does not create records; malformed/private URLs and oversized batches are refused',async()=>{const {env,sqlite}=setup();await kakaoWebhook(request('안녕'),env);assert.equal((sqlite.prepare('SELECT COUNT(*) AS n FROM capture_jobs').get() as {n:number}).n,0);assert.throws(()=>normalizeUrl('http://127.0.0.1/admin'));assert.throws(()=>normalizeUrl('file:///etc/passwd'));assert.throws(()=>normalizeUrl('https://name:password@example.com'));assert.throws(()=>urlsFromMessage(Array(6).fill('https://example.com').join(' ')));assert.deepEqual(urlsFromMessage('읽어봐 (https://example.com/a).'),['https://example.com/a'])});
test('processor commits once and keeps received timestamp; repeat delivery does not rerun analysis',async()=>{const {env,sqlite}=setup();await kakaoWebhook(request('https://example.com/a'),env);const before=sqlite.prepare('SELECT * FROM capture_jobs').get() as {id:string;created_at:string};assert.equal(await processNext(env,fake),true);assert.equal(await processNext(env,fake),false);const row=sqlite.prepare('SELECT * FROM contents').get() as {id:string;created_at:string;owner:string};assert.equal(row.id,before.id);assert.equal(row.created_at,before.created_at);assert.equal(row.owner,await kakaoOwner('test-bot','user-a'));assert.match(await answer(await kakaoWebhook(request('요약'),env)),/저장한 원문에서 얻은 결과/);assert.match(await answer(await kakaoWebhook(request('요약','user-b'),env)),/아직 저장한 링크가 없/)});
test('failure preserves URL, backs off, terminates after three attempts and can be retried by owner',async()=>{const {env,sqlite}=setup();await kakaoWebhook(request('https://example.com/fail'),env);const fail=async():Promise<Item>=>{throw new Error('provider unavailable')};await processNext(env,fail);let row=sqlite.prepare('SELECT * FROM capture_jobs').get() as {status:string;url:string;available_at:number};assert.equal(row.status,'retry');assert.equal(row.url,'https://example.com/fail');assert.ok(row.available_at>Date.now());assert.equal(await processNext(env,fail),false);for(let i=0;i<2;i++){sqlite.exec('UPDATE capture_jobs SET available_at=0');await processNext(env,fail)}row=sqlite.prepare('SELECT * FROM capture_jobs').get() as typeof row;assert.equal(row.status,'failed');await kakaoWebhook(request('다시 시도','user-b'),env);assert.equal((sqlite.prepare('SELECT status FROM capture_jobs').get() as {status:string}).status,'failed');await kakaoWebhook(request('다시 시도'),env);assert.equal((sqlite.prepare('SELECT status FROM capture_jobs').get() as {status:string}).status,'queued')});
test('lease expiration recovers interrupted jobs; stale worker cannot overwrite a newer result',async()=>{const {env,sqlite}=setup();await kakaoWebhook(request('https://example.com/lease'),env);sqlite.exec("UPDATE capture_jobs SET status='processing', attempts=1,lease_until=0,lease_token='old'");await processNext(env,fake);assert.equal((sqlite.prepare('SELECT status FROM capture_jobs').get() as {status:string}).status,'ready');sqlite.exec("DELETE FROM contents; UPDATE capture_jobs SET status='queued',attempts=0");await processNext(env,async url=>{sqlite.exec("UPDATE capture_jobs SET lease_token='new-owner'");return fake(url)});assert.equal((sqlite.prepare('SELECT COUNT(*) AS n FROM contents').get() as {n:number}).n,0);sqlite.exec("UPDATE capture_jobs SET status='processing',attempts=3,lease_until=0");await drain(env);assert.equal((sqlite.prepare('SELECT status FROM capture_jobs').get() as {status:string}).status,'failed')});
test('unreadable content remains stored and explicitly marked needs_content',async()=>{const {env,sqlite}=setup();await kakaoWebhook(request('https://www.instagram.com/p/example'),env);await processNext(env,async url=>({...await fake(url),mode:'unread',summary:'본문 확인 필요'}));assert.equal((sqlite.prepare('SELECT status FROM capture_jobs').get() as {status:string}).status,'needs_content');assert.match(await answer(await kakaoWebhook(request('보관함'),env)),/본문 확인 필요/)});
test('iOS capture pairs once, authenticates, stores once and reports today count',async()=>{const {env,sqlite}=setup();const owner='kakao:test-owner';await env.DB.prepare('INSERT INTO users (id,created_at) VALUES (?,?)').bind(owner,new Date().toISOString()).run();const code=await createPairingCode(env,owner);const paired=await pairDevice(new Request('https://ingress.example.com/auth/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})}),env);assert.equal(paired.status,200);const {token}=await paired.json() as {token:string};assert.equal((await pairDevice(new Request('https://ingress.example.com/auth/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})}),env)).status,401);const send=(url:string,secret=token)=>shortcutCapture(new Request('https://ingress.example.com/captures/shortcut',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json'},body:JSON.stringify({url})}),env);assert.equal((await send('https://example.com/a','wrong')).status,401);let response=await send('추천 https://example.com/a?utm_source=share');assert.equal(response.status,200);let body=await response.json() as {saved:boolean;duplicate:boolean;today:number};assert.equal(body.saved,true);assert.equal(body.today,1);response=await send('https://example.com/a');body=await response.json() as typeof body;assert.equal(body.duplicate,true);assert.equal(body.today,1);const row=sqlite.prepare('SELECT owner,source,status,url FROM capture_jobs').get() as {owner:string;source:string;status:string;url:string};assert.deepEqual({...row},{owner,source:'ios_shortcut',status:'queued',url:'https://example.com/a'});});
test('paired device can read only its unified Kakao and iOS library',async()=>{const {env}=setup();const owner='kakao:library-owner';await env.DB.prepare('INSERT INTO users (id,created_at) VALUES (?,?)').bind(owner,new Date().toISOString()).run();const code=await createPairingCode(env,owner);const paired=await pairDevice(new Request('https://ingress.example.com/auth/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})}),env);const {token}=await paired.json() as {token:string};await env.DB.prepare("INSERT INTO capture_jobs (id,owner,url,source,status,attempts,available_at,created_at) VALUES (?,?,?,?, 'queued',0,?,?)").bind('mine',owner,'https://example.com/mine','kakao',Date.now(),new Date().toISOString()).run();await env.DB.prepare("INSERT INTO capture_jobs (id,owner,url,source,status,attempts,available_at,created_at) VALUES (?,?,?,?, 'queued',0,?,?)").bind('other','kakao:other','https://example.com/other','kakao',Date.now(),new Date().toISOString()).run();const response=await deviceLibrary(new Request('https://ingress.example.com/captures',{headers:{Authorization:`Bearer ${token}`}}),env);assert.equal(response.status,200);const body=await response.json() as {items:{id:string;url:string}[]};assert.deepEqual(body.items.map(item=>item.id),['mine']);assert.equal(body.items[0].url,'https://example.com/mine');assert.equal((await deviceLibrary(new Request('https://ingress.example.com/captures'),env)).status,401);});
test('email account logs in and absorbs an existing Kakao library',async()=>{const {env,sqlite}=setup();const credentials={email:'Hello@Nuff.test',password:'long-password-123'};let response=await signup(new Request('https://ingress.example.com/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(credentials)}),env);assert.equal(response.status,200);const {token}=await response.json() as {token:string};assert.equal((await signup(new Request('https://ingress.example.com/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(credentials)}),env)).status,409);response=await login(new Request('https://ingress.example.com/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:credentials.email,password:'wrong-password'})}),env);assert.equal(response.status,401);response=await login(new Request('https://ingress.example.com/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(credentials)}),env);assert.equal(response.status,200);const kakao='kakao:merge-source',now=new Date().toISOString();await env.DB.batch([env.DB.prepare('INSERT INTO users (id,created_at) VALUES (?,?)').bind(kakao,now),env.DB.prepare('INSERT INTO user_identities (id,user_id,provider,provider_subject,created_at) VALUES (?,?,?,?,?)').bind('kakao-id',kakao,'kakao',kakao,now),env.DB.prepare("INSERT INTO capture_jobs (id,owner,url,source,status,attempts,available_at,created_at) VALUES (?,?,?,?, 'queued',0,?,?)").bind('from-kakao',kakao,'https://example.com/from-kakao','kakao',Date.now(),now)]);const code=await createPairingCode(env,kakao);response=await linkKakao(new Request('https://ingress.example.com/auth/link-kakao',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({code})}),env);assert.equal(response.status,200);const emailUser=(sqlite.prepare('SELECT user_id FROM email_credentials WHERE email=?').get('hello@nuff.test') as {user_id:string}).user_id;assert.equal((sqlite.prepare("SELECT owner FROM capture_jobs WHERE id='from-kakao'").get() as {owner:string}).owner,emailUser);assert.equal((sqlite.prepare("SELECT user_id FROM user_identities WHERE provider='kakao'").get() as {user_id:string}).user_id,emailUser);});
test('a legacy Kakao account can add email login without moving its library',async()=>{const {env}=setup();const owner='kakao:upgrade-owner',now=new Date().toISOString();await env.DB.prepare('INSERT INTO users (id,created_at) VALUES (?,?)').bind(owner,now).run();const code=await createPairingCode(env,owner);const paired=await pairDevice(new Request('https://x.test/auth/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})}),env);const {token}=await paired.json() as {token:string};const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};const added=await addEmail(new Request('https://x.test/auth/add-email',{method:'POST',headers,body:JSON.stringify({email:'legacy@nuff.test',password:'long-password-123'})}),env);assert.equal(added.status,200);const info=await accountInfo(new Request('https://x.test/auth/me',{headers:{Authorization:`Bearer ${token}`}}),env);assert.equal((await info.json() as {user:{email:string}}).user.email,'legacy@nuff.test');const logged=await login(new Request('https://x.test/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'legacy@nuff.test',password:'long-password-123'})}),env);assert.equal(logged.status,200)});
test('a logged-in app can create a one-time code for its share extension',async()=>{const {env}=setup();const created=await signup(new Request('https://x.test/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'device@nuff.test',password:'long-password-123'})}),env);const {token}=await created.json() as {token:string};const codeResponse=await createDeviceCode(new Request('https://x.test/auth/device-code',{method:'POST',headers:{Authorization:`Bearer ${token}`}}),env);assert.equal(codeResponse.status,200);const {code}=await codeResponse.json() as {code:string};assert.equal(code.length,8);const paired=await pairDevice(new Request('https://x.test/auth/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})}),env);assert.equal(paired.status,200);assert.equal((await pairDevice(new Request('https://x.test/auth/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})}),env)).status,401)});
test('YouTube URLs are recognized and official metadata becomes readable content',async()=>{assert.equal(youtubeVideoId('https://youtu.be/dQw4w9WgXcQ?t=1'),'dQw4w9WgXcQ');assert.equal(youtubeVideoId('https://www.youtube.com/shorts/dQw4w9WgXcQ'),'dQw4w9WgXcQ');assert.equal(youtubeVideoId('https://example.com/watch?v=dQw4w9WgXcQ'),null);const original=globalThis.fetch;globalThis.fetch=async input=>{const url=new URL(String(input));assert.equal(url.hostname,'www.googleapis.com');assert.equal(url.searchParams.get('id'),'dQw4w9WgXcQ');assert.equal(url.searchParams.get('key'),'test-key');return Response.json({items:[{snippet:{title:'테스트 영상',description:'설명이 충분히 길어서 영상의 핵심 내용과 맥락을 분석할 수 있습니다. 이 문장은 읽기 가능한 최소 길이를 넘기기 위해 반복되는 테스트 설명입니다. 영상은 사용자가 저장한 정보를 나중에 다시 찾도록 돕는 방법을 소개합니다.',channelTitle:'Nuff 연구소',publishedAt:'2026-09-24T00:00:00Z',tags:['PKM','정보관리']}}]})};try{const result=await extract('https://www.youtube.com/watch?v=dQw4w9WgXcQ',undefined,{YOUTUBE_API_KEY:'test-key'});assert.equal(result.title,'테스트 영상');assert.equal(result.readable,true);assert.match(result.text,/Nuff 연구소/);assert.match(result.text,/정보관리/)}finally{globalThis.fetch=original}});
test('Instagram preview metadata is saved without running AI analysis',async()=>{const original=globalThis.fetch;globalThis.fetch=async input=>{const url=new URL(String(input));if(url.hostname==='cloudflare-dns.com')return Response.json({Answer:[{type:1,data:'157.240.1.1'}]});return new Response('<html><head><meta content="릴스 제목" property="og:title"><meta property="og:description" content="게시물에 적힌 짧은 설명입니다."><meta property="og:image" content="https://cdn.example.com/reel.jpg"></head><body></body></html>',{headers:{'Content-Type':'text/html'}})};try{const item=await analyzeContent('https://www.instagram.com/reel/example/',undefined,{OPENAI_API_KEY:'unused'},()=>{});assert.equal(item.title,'릴스 제목');assert.equal(item.summary,'게시물에 적힌 짧은 설명입니다.');assert.equal(item.thumbnail,'https://cdn.example.com/reel.jpg');assert.equal(item.platform,'Instagram');assert.equal(item.mode,'unread')}finally{globalThis.fetch=original}});
test('Gemini analyzes a public YouTube URL into the Nuff schema',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input,init)=>{assert.equal(String(input),'https://generativelanguage.googleapis.com/v1beta/interactions');assert.equal(new Headers(init?.headers).get('x-goog-api-key'),'gemini-test-key');const body=JSON.parse(String(init?.body)) as {input:{type:string;uri?:string}[];store:boolean};assert.equal(body.store,false);assert.equal(body.input[1].uri,'https://www.youtube.com/watch?v=dQw4w9WgXcQ');return Response.json({output_text:JSON.stringify({title:'영상 제목',summary:'영상의 핵심을 설명합니다.',keywords:['지식','영상','요약'],topic:'생산성 & 집중',claims:['중요한 정보를 다시 찾을 수 있어야 한다.']})})};try{const item=await analyzeContent('https://www.youtube.com/shorts/dQw4w9WgXcQ',undefined,{GEMINI_API_KEY:'gemini-test-key'},()=>{});assert.equal(item.mode,'ai');assert.equal(item.platform,'YouTube');assert.equal(item.title,'영상 제목');assert.match(item.summary,/핵심/)}finally{globalThis.fetch=original}});

function authRequest(path:string,body:unknown,token?:string){return new Request(`https://x.test/auth/${path}`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)})}
test('share setup creates no content and saves to the email account without Kakao',async()=>{
 const {env,sqlite}=setup();
 const account=await (await signup(authRequest('signup',{email:'share-only@nuff.test',password:'long-password-123'}),env)).json() as {token:string;user:{id:string}};
 const {code}=await (await createDeviceCode(authRequest('device-code',{},account.token),env)).json() as {code:string};
 const paired=await (await pairDevice(authRequest('pair',{code}),env)).json() as {token:string};
 assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM capture_jobs').get()!.n,0);
 await shortcutCapture(new Request('https://x.test/captures/shortcut',{method:'POST',headers:{Authorization:`Bearer ${paired.token}`,'Content-Type':'application/json'},body:JSON.stringify({url:'https://example.com/first-link'})}),env);
 assert.equal(sqlite.prepare('SELECT owner FROM capture_jobs').get()!.owner,account.user.id);
 const library=await (await deviceLibrary(new Request('https://x.test/captures',{headers:{Authorization:`Bearer ${account.token}`}}),env)).json() as {items:unknown[]};
 assert.equal(library.items.length,1);
 assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM user_identities WHERE provider='kakao'").get()!.n,0);
});
test('Kakao linking rejects share codes and never merges two email accounts',async()=>{
 const {env,sqlite}=setup();
 const create=async(email:string)=>await (await signup(authRequest('signup',{email,password:'long-password-123'}),env)).json() as {token:string;user:{id:string}};
 const target=await create('target@nuff.test'),source=await create('source@nuff.test');
 const code=await createPairingCode(env,source.user.id);
 assert.equal((await linkKakao(authRequest('link-kakao',{code},target.token),env)).status,400);
 assert.equal(sqlite.prepare('SELECT used_at FROM pairing_codes').get()!.used_at,null);
 sqlite.prepare('INSERT INTO user_identities (id,user_id,provider,provider_subject,created_at) VALUES (?,?,?,?,?)').run('existing-kakao',source.user.id,'kakao','kakao:existing',new Date().toISOString());
 assert.equal((await linkKakao(authRequest('link-kakao',{code},target.token),env)).status,409);
 assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM email_credentials').get()!.n,2);
 assert.equal(sqlite.prepare('SELECT used_at FROM pairing_codes').get()!.used_at,null);
});
test('verified email cannot issue a session using an arbitrary verification code',async()=>{
 const {env,sqlite}=setup();
 await signup(authRequest('signup',{email:'verified@nuff.test',password:'long-password-123'}),env);
 const count=sqlite.prepare('SELECT COUNT(*) AS n FROM device_tokens').get()!.n;
 const response=await verifyEmail(authRequest('verify-email',{email:'verified@nuff.test',code:'123456'}),env);
 assert.equal(response.status,401);
 assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM device_tokens').get()!.n,count);
});
