import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/lib/storage';
import { analyzeContent, normalizeUrl, AIConfig } from '@/lib/pipeline';
const headers={'Cache-Control':'no-store'};
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'로그인이 필요해요.'},{status:401,headers});try{const rows=await database().prepare('SELECT data, viewed FROM contents WHERE owner = ? ORDER BY created_at DESC').bind(user.userId).all<{data:string;viewed:number}>();const actions=await database().prepare("SELECT detail, created_at FROM events WHERE owner = ? AND kind = 'action' ORDER BY created_at DESC LIMIT 1").bind(user.userId).first();return Response.json({items:rows.results.map(r=>({...JSON.parse(r.data),viewed:!!r.viewed})),action:actions?.detail||null,aiConfigured:!!(env as unknown as AIConfig).OPENAI_API_KEY},{headers});}catch{return Response.json({error:'보관함을 불러오지 못했어요. 잠시 후 다시 시도해주세요.'},{status:503,headers});}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'로그인이 필요해요.'},{status:401});if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'허용되지 않은 요청입니다.'},{status:403});let url:string,pasted:string|undefined;try{const body=await request.json() as {url?:unknown;text?:unknown};if(typeof body.url!=='string'||body.url.length>4096||body.text!==undefined&&(typeof body.text!=='string'||body.text.length>24000))throw new Error('링크와 본문 길이를 확인해주세요.');url=normalizeUrl(body.url);pasted=body.text as string|undefined;}catch(e){return Response.json({error:e instanceof Error?e.message:'입력을 확인해주세요.'},{status:400});}
 try{const existing=await database().prepare('SELECT id FROM contents WHERE owner = ? AND url = ?').bind(user.userId,url).first();if(existing&&!pasted)return Response.json({error:'이미 저장한 링크예요. 보관함에서 확인해주세요.'},{status:409});
 const encoder=new TextEncoder();const stream=new ReadableStream({async start(controller){const send=(data:unknown)=>controller.enqueue(encoder.encode(JSON.stringify(data)+'\n'));try{const item=await analyzeContent(url,pasted,env as unknown as AIConfig,message=>send({stage:message}));if(existing)item.id=String(existing.id);const db=database();if(existing)await db.prepare('UPDATE contents SET data = ? WHERE id = ? AND owner = ?').bind(JSON.stringify(item),item.id,user.userId).run();else await db.batch([db.prepare('INSERT INTO contents (id,owner,url,data,created_at) VALUES (?,?,?,?,?)').bind(item.id,user.userId,item.url,JSON.stringify(item),item.createdAt),db.prepare('INSERT INTO events (id,owner,kind,item_id,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,'save',item.id,item.createdAt)]);send({item});}catch(e){send({error:e instanceof Error&&e.message.startsWith('AI')?e.message:'저장하지 못했어요. 링크가 이미 저장되었는지 확인하고 다시 시도해주세요.'});}finally{controller.close();}}});return new Response(stream,{headers:{...headers,'Content-Type':'application/x-ndjson'}});}catch{return Response.json({error:'저장소에 연결하지 못했어요. 다시 시도해주세요.'},{status:503});}}
